cp .env.example ./.env;
docker compose up -d --build;
docker compose exec app composer install;
docker compose exec app composer update;
docker compose exec app php artisan migrate;
docker compose exec app php artisan key:generate;
docker compose exec app php artisan config:cache;
docker compose exec app php artisan migrate;
docker compose exec app php artisan queue:work;
echo "proyecto deployeado exitosamente";
